[package]
name = "advent_of_code_2019"
version = "0.1.0"
edition = "2021"

[dependencies]

[lib]
name = "intcode"
path = "src/lib/intcode/intcode.rs"

[[bin]]
name = "day-02"
path = "src/bin/day-02/main.rs"
